apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    k8s-app: aci-containers
data:
  controller_config: |-
    {
        "log-level": "debug",
        "default-endpoint-group": {
            "policy-space": "demo",
            "name": "kubernetes-default|default"
        },
        "service-ip-pool": [
            {"start": "10.4.1.1", "end": "10.4.255.254"}
        ],
        "static-service-ip-pool": [
            {"start": "10.4.0.1", "end": "10.4.0.255"}
        ],
        "pod-ip-pool": [
            {"start": "10.1.0.2", "end": "10.1.255.254"}
        ],
        "node-service-ip-pool": [
            {"start": "10.6.1.1", "end": "10.6.1.254"}
        ]
    }
  host_agent_config: |-
    {
        "log-level": "debug",
        "aci-vrf": "kubernetes-vrf",
        "aci-vrf-tenant": "common",
        "service-iface": "eth2",
        "service-iface-vlan": 4003,
        "cni-netconfig": [
            {
                "subnet": "10.1.0.0/16",
                "gateway": "10.1.0.1",
                "routes": [
                    { "dst": "0.0.0.0/0", "gw": "10.1.0.1" }
                ]
            }
        ]
    }
  opflex_agent_config: |-
    {
        "opflex": {
            "domain": "comp/prov-OpenStack/ctrlr-[ostack]-ostack/sw-InsiemeLSOid"
        },
        "renderers": {
            "stitched-mode": {
                "int-bridge-name": "br-int",
                "access-bridge-name": "br-access",
                "encap": {
                    "vxlan" : {
                        "encap-iface": "br-int_vxlan0",
                        "uplink-iface": "eth2.4093",
                        "uplink-vlan": 4093,
                        "remote-ip": "10.0.0.32",
                        "remote-port": 8472
                    }
                }
            }
        }
    }
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    k8s-app: aci-containers
spec:
  template:
    metadata:
      labels:
        name: aci-containers-host
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
        - name: aci-containers-host
          image: noiro/aci-containers-host
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: noiro/opflex
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: noiro/opflex
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host_agent_config
                path: host-agent.conf
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex_agent_config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    k8s-app: aci-containers
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key":"CriticalAddonsOnly", "operator":"Exists"}]
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        k8s-app: aci-containers
    spec:
      hostNetwork: true
      containers:
        - name: aci-containers-controller
          image: noiro/aci-containers-controller
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
      volumes:
        - name: config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller_config
                path: controller.conf
