apiVersion: v1
kind: ConfigMap
metadata:
  name: aci-containers-config
  namespace: kube-system
  labels:
    network-plugin: aci-containers
data:
  encap-type: {{ config.node_config.encap_type|yaml_quote }}
  uplink-iface: {{ config.node_config.uplink_iface|yaml_quote }}
  infra-vlan: {{ config.node_config.infra_vlan|yaml_quote }}
  vxlan-uplink-iface: {{ config.node_config.vxlan_uplink_iface|yaml_quote }}
  apic-hosts: {{ config.aci_config.apic_hosts|join(',')|yaml_quote }}
  controller-config: |-
    {
        "log-level": "{{config.logging.controller_log_level}}",
        "aci-vmm-pod": "{{config.aci_config.vmm_domain.pod}}",
        "aci-vmm-domain": "{{config.aci_config.vmm_domain.domain}}",
        "aci-vmm-controller": "{{config.aci_config.vmm_domain.controller}}",
        "aci-policy-tenant": "{{config.kubernetes_config.default_endpoint_group.tenant}}",
        "aci-service-phys-dom": "{{config.aci_config.physical_domain.domain}}",
        "aci-service-encap": "vlan-{{config.node_config.service_vlan}}",
        "aci-l3out-tenant": "{{config.kubernetes_config.aci_l3out.tenant}}",
        "aci-l3out": "{{config.kubernetes_config.aci_l3out.name}}",
        "aci-ext-networks": {{ config.kubernetes_config.aci_l3out.external_networks|json|indent(width=8) }},
        "aci-vrf": "{{config.kubernetes_config.aci_vrf.name}}",
        "default-endpoint-group": {
            "policy-space": "{{config.kubernetes_config.default_endpoint_group.tenant}}",
            "name": "{{config.kubernetes_config.default_endpoint_group.app_profile}}|{{config.kubernetes_config.default_endpoint_group.group}}"
        },
        "service-ip-pool": {{ config.kubernetes_config.service_ip_pool|json|indent(width=8) }},
        "static-service-ip-pool": {{ config.kubernetes_config.static_service_ip_pool|json|indent(width=8) }},
        "pod-ip-pool": {{ config.kubernetes_config.pod_ip_pool|json|indent(width=8) }},
        "node-service-ip-pool": {{ config.kubernetes_config.node_service_ip_pool|json|indent(width=8) }},
        "node-service-subnets": {{ config.kubernetes_config.node_service_gw_subnets|json|indent(width=8) }}
    }
  host-agent-config: |-
    {
        "log-level": "{{config.logging.hostagent_log_level}}",
        "aci-vrf": "{{config.kubernetes_config.aci_vrf.name}}",
        "aci-vrf-tenant": "{{config.kubernetes_config.aci_vrf.tenant}}",
        "service-iface": "{{ config.node_config.uplink_iface }}",
        "service-iface-vlan": {{ config.node_config.service_vlan }},
        "cni-netconfig": {{ config.kubernetes_config.pod_network|json|indent(width=8) }}
    }
  opflex-agent-config: |-
    {
        "log": {
            "level": "{{config.logging.opflexagent_log_level}}"
        },
        "opflex": {
            "domain": "comp/prov-Kubernetes/ctrlr-[{{config.aci_config.vmm_domain.domain}}]-{{config.aci_config.vmm_domain.controller}}/sw-InsiemeLSOid"
        }
    }
  aim-config: |-
    [DEFAULT]
    debug = {{config.logging.aim_debug}}
---
apiVersion: v1
kind: Secret
metadata:
  name: apic-user-pass
  namespace: kube-system
data:
  username: {{config.aci_config.apic_login.username|base64enc}}
  password: {{config.aci_config.apic_login.password|base64enc}}
---
apiVersion: extensions/v1beta1
kind: ThirdPartyResource
description: ACI policy model objects to be synchronized with ACI
metadata:
  name: aci.acicontainers.cisco.com
versions:
- name: v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-controller
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    network-plugin: aci-containers
  name: aci-containers:controller
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - deployments
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - "extensions"
  resources:
  - thirdpartyresources
  verbs:
  - get
- apiGroups:
  - "acicontainers.cisco.com"
  resources:
  - acis
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
  - deletecollection
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    network-plugin: aci-containers
  name: aci-containers:host-agent
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - list
  - watch
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aci-containers:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:controller
subjects:
- kind: ServiceAccount
  name: aci-containers-controller
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: aci-containers:host-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aci-containers:host-agent
subjects:
- kind: ServiceAccount
  name: aci-containers-host-agent
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-host
  namespace: kube-system
  labels:
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aci-containers-host
        network-plugin: aci-containers
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      serviceAccountName: aci-containers-host-agent
      containers:
        - name: aci-containers-host
          image: {{ config.container_registry_prefix }}/aci-containers-host
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: cni-bin
              mountPath: /mnt/cni-bin
            - name: cni-conf
              mountPath: /mnt/cni-conf
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: host-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8090
        - name: opflex-agent
          image: {{ config.container_registry_prefix }}/opflex
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: ACI_ENCAP_TYPE
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: encap-type
            - name: ACI_UPLINK_IFACE
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: uplink-iface
            - name: ACI_VXLAN_IFACE
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: vxlan-uplink-iface
            - name: ACI_INFRA_VLAN
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: infra-vlan
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: opflex-config-volume
              mountPath: /usr/local/etc/opflex-agent-ovs/conf.d
        - name: mcast-daemon
          image: {{ config.container_registry_prefix }}/opflex
          command: ["/bin/sh"]
          args: ["/usr/local/bin/launch-mcastdaemon.sh"]
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
      restartPolicy: Always
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt
        - name: cni-conf
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: host-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: host-agent-config
                path: host-agent.conf
        - name: opflex-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: opflex-agent-config
                path: local.conf
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: aci-containers-openvswitch
  namespace: kube-system
  labels:
    network-plugin: aci-containers
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: aci-containers-openvswitch
        network-plugin: aci-containers
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      containers:
        - name: aci-containers-openvswitch
          image: {{ config.container_registry_prefix }}/openvswitch
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          env:
            - name: ACI_ENCAP_TYPE
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: encap-type
            - name: ACI_UPLINK_IFACE
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: uplink-iface
            - name: OVS_RUNDIR
              value: /usr/local/var/run/openvswitch
          volumeMounts:
            - name: hostvar
              mountPath: /usr/local/var
            - name: hostrun
              mountPath: /run
            - name: hostrun
              mountPath: /usr/local/run
            - name: hostetc
              mountPath: /usr/local/etc
            - name: hostmodules
              mountPath: /lib/modules
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-ovs.sh
      restartPolicy: Always
      volumes:
        - name: hostetc
          hostPath:
            path: /etc
        - name: hostvar
          hostPath:
            path: /var
        - name: hostrun
          hostPath:
            path: /run
        - name: hostmodules
          hostPath:
            path: /lib/modules
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aci-containers-controller
  namespace: kube-system
  labels:
    network-plugin: aci-containers
    k8s-app: aci-containers-controller
    name: aci-containers-controller
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key":"CriticalAddonsOnly", "operator":"Exists"}]
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: aci-containers-controller
      namespace: kube-system
      labels:
        network-plugin: aci-containers
        k8s-app: aci-containers-controller
        name: aci-containers-controller
    spec:
      hostNetwork: true
      serviceAccountName: aci-containers-controller
      containers:
        - name: aci-containers-controller
          image: {{ config.container_registry_prefix }}/aci-containers-controller
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: controller-config-volume
              mountPath: /usr/local/etc/aci-containers/
          livenessProbe:
            httpGet:
              path: /status
              port: 8091
        - name: aci-integration-module
          image: {{ config.container_registry_prefix }}/aci-integration-module
          imagePullPolicy: IfNotPresent
          env:
            - name: APIC_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: apic-hosts
            - name: APIC_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: aci-containers-config
                  key: apic-hosts
            - name: APIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: apic-user-pass
                  key: username
            - name: APIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apic-user-pass
                  key: password
            - name: APIC_VMM_POD
              value: "{{config.aci_config.vmm_domain.pod}}"
            - name: APIC_L3OUT_TENANT
              value: "{{config.kubernetes_config.aci_l3out.tenant}}"
          volumeMounts:
            - name: aim-config-volume
              mountPath: /usr/local/etc/aim-local
      volumes:
        - name: controller-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: controller-config
                path: controller.conf
        - name: aim-config-volume
          configMap:
            name: aci-containers-config
            items:
              - key: aim-config
                path: aim-local.conf

